server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tms?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-test-query: SELECT 1
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.paob.tms.controller

logging:
  level:
    root: info
    com.paob.tms: debug
    org.springframework: info
    org.hibernate: info
    org.mybatis: info